"use client"
import { Inter } from "next/font/google";
import { useRouter } from 'next/navigation'; // استخدم useRouter من next/navigation
import { useEffect } from 'react';
import { auth } from './firebase/Firebasepage'; // تأكد من استيراد ملف Firebase بشكل صحيح
import { onAuthStateChanged } from 'firebase/auth';
import '@fortawesome/fontawesome-free/css/all.min.css';
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      if (!user) {
        router.push('/loginPage'); // تأكد من توجيه المستخدم إلى صفحة تسجيل الدخول
      }
    });

    return () => unsubscribe(); // تنظيف الاشتراك عند إلغاء تحميل المكون
  }, [router]);

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}




